name: Update Azure Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: <your-azure-function-app-name>
          slot-name: <your-azure-function-slot-name> # Optional, if using deployment slots
          publish-profile: ${{ secrets.AZURE_FUNCTION_APP_PUBLISH_PROFILE }}

      - name: Deploy to Azure Functions
        uses: azure/functions-action@v1
        with:
          app-name: <your-azure-function-app-name>
          slot-name: <your-azure-function-slot-name> # Optional, if using deployment slots
          publish-profile: ${{ secrets.AZURE_FUNCTION_APP_PUBLISH_PROFILE }}
