jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: . # The build context directory. Default is the repository root.
          file: ./path/to/Dockerfile # The path to the Dockerfile. Default is Dockerfile.
          push: true # Whether to push the built image. Default is false.
          tags: yourusername/yourrepository:latest # The tags to apply to the built image. Can be a single tag or a list of tags.
          labels: key1=value1,key2=value2 # Optional. A comma-separated list of labels to apply to the built image.
          build-args: |
            ARG1=value1
            ARG2=value2 # Optional. Build-time variables to pass to the Docker build process.
          cache-from: type=local,src=path/to/cache # Optional. Specify a cache source to use during the build.
          cache-to: type=local,dest=path/to/cache # Optional. Specify a cache destination to use after the build.
          target: target_stage # Optional. Specify a build stage to build.
          file-digest: sha256:<digest> # Optional. The digest of the Dockerfile being built.
          secret-file: path/to/secret/file # Optional. Specify the path to a secret file to be used during the build.
          outputs: type=registry,registry=$DOCKER_REGISTRY,repository=$DOCKER_REPO,image=$DOCKER_IMAGE # Optional. Specify the outputs to use after the build.
          platforms: linux/amd64,linux/arm64 # Optional. Specify platforms for which to build the image.
          pull-repository: true # Optional. Whether to pull the repository before building. Default is false.
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional. Specify the GitHub token to use for pulling the repository.
