name: Expressions and Contexts
# on: [push, pull_request, issues, workflow_dispatch]
on: [push]
run-name: "Expressions and Contexts by ${{ github.actor }}, event: ${{ github.event_name }}"


jobs: 
    using-expresssions-and-contexts:
        runs-on: ubuntu-latest
        run: if github.event_name == 'push'
        steps:
            - name: Expressions
              id: expressions
              run: | 
                echo ${{ 1 }}
                echo ${{ 'This is string' }}
                echo ${{ null }}
                echo ${{ true }}
                echo ${{ 1>2 }}
                echo ${{ 'string'== 'String' }}
                echo ${{ true && false }}
                echo ${{ true || (false && true) }}

            # - name: Dump Contexts
            #   run: | 
            #     echo ${{ toJson(job) }}
            #     echo ${{ toJson(steps) }}
            #     echo ${{ toJson(runner) }}
            #     echo ${{ toJson(matrix) }}
            #     echo ${{ toJson(strategy) }}
            #     echo ${{ toJson(inputs) }}
            #     echo ${{ toJson(secrets) }}
            #     echo ${{ toJson(job.statuses) }}
            #     echo ${{ toJson(job.outputs) }}
            #     echo ${{ toJson(job.steps) }}  
            