name: first-workflow
on: [push]

jobs: 
    run-shell-command:
        runs-on: ubuntu-late st
        steps:
            - name: Run a one-line script
              run: echo Hello, world!
            - name: Run a multi-line script
              run: |
                node -v
                npm -v