name: first-workflow
on: [push]

jobs: 
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
            - name: Run a one-line script
              run: echo Hello, world!
            - name: Run a multi-line script
              run: |
                node -v
                npm -v
    parallel-job-macos: 
        runs-on: macos-latest
        steps:
            - name: Run a one-line script
              run: echo Hello, world!
            - name: Run a multi-line script
              run: |
                node -v
                npm -v
    dependent-job:
        runs-on: windows-latest
        needs: [run-shell-command, parallel-job-macos]
        steps:
            - name: Run a one-line script
              run: Write-OutPut "Hello, world!"
            - name: Error Step
              run: ping localhost 