name: Checkout
on: [push]


jobs: 
    checkout-action:
      runs-on: ubuntu-latest
      steps: 
        - name: List files befor
          run: ls -la
        - uses: actions/checkout@v3
        - name: List after files
          run: ls -la