name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      input1:
        description: "First input"
        required: true
        default: "Default Value 1"
      input2:
        description: "Second input"
        required: true
        default: "Default Value 2"

jobs:
  create-outputs:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.set-output.outputs.output1 }}
      output2: ${{ steps.set-output.outputs.output2 }}
    steps:
      - name: Set outputs
        id: set-output
        run: |
          echo "output1=${{ github.event.inputs.input1 }}" >> $GITHUB_OUTPUT
          echo "output2=${{ github.event.inputs.input2 }}" >> $GITHUB_OUTPUT
