name: Tag workflow

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Select repository'
        type: choice
        options:
          - laptop
          - desktop
          - ipad
        required: true
      source_branch:
          description: 'Select Source Branch'
          required: true
      version_type:
        description: 'Select Version Type'
        type: choice
        options:
          - Major/Release
          - Minor/Release
          - Patch/Hotfix
