name: Artifact Sharing Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Artifact File
        run: echo "Hello from the build job!" > shared_file.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: shared-files
          path: shared_file.txt

  consume:
    runs-on: ubuntu-latest
    needs: build  # Specifies dependency on the 'build' job
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: shared-files

      - name: Read Shared File
        run: cat shared_file.txt
