name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      input1:
        description: "First input"
        required: true
        default: "Default Value 1"
      input2:
        description: "Second input"
        required: true
        default: "Default Value 2"

jobs:
  create-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Save inputs to files
        run: |
          echo "${{ github.event.inputs.input1 }}" > input1.txt
          echo "${{ github.event.inputs.input2 }}" > input2.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: workflow-inputs
          path: "*.txt"

jobs:
  process-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: workflow-inputs

      - name: Read inputs from files
        run: |
          echo "Input 1: $(cat input1.txt)"
          echo "Input 2: $(cat input2.txt)"
