name: multi-matrix
on: [push]

jobs:
    node-matrix:
        continue-on-error: false # default: false, this will continue the build if one of the matrix fails
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                node-version: [14, 15, 16]
                include:
                    - os: ubuntu-latest
                      node-version: 14
                    - os: ubuntu-latest
                      node-version: 15
                    - os: ubuntu-latest
                      node-version: 16
                    - os: windows-latest
                      node-version: 14
                    - os: windows-latest
                      node-version: 15
                    - os: windows-latest
                      node-version: 16
            fail-fast: false  # default: true, this will stop the build if one of the matrix fails
            # max-parallel: 3
        runs-on: ${{ matrix.os }} # runs on ubuntu and windows
        steps:
            - run: node -v
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: node -v