name: One Click Deploment- backupfile
on: 
  workflow_dispatch:
     inputs:
            subject:
                description: 'Select a subject'
                required: true
                default: 'english'
                type: choice
                options:
                    - english
                    - science
                    - social
                    - maths

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        az webapp list --query "[?state=='Running']" -o table
