name: One Click
on: 
  workflow_dispatch:
     inputs:
        tag_name:
          description: 'Tag name to apply'
          required: true
          default: 'v1.0.0'

jobs:
  pull_and_tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [
          'owner/repo1',
          'owner/repo2',
          'owner/repo3',
          'owner/repo4',
          'owner/repo5',
          'owner/repo6',
          'owner/repo7',
          'owner/repo8',
          'owner/repo9',
          'owner/repo10'
        ]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: ${{ matrix.repo }}
        token: ${{ secrets.PAT }}
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Create and push tag
      run: |
        git tag ${{ github.event.inputs.tag_name }}
        git push origin ${{ github.event.inputs.tag_name }}
