name: One Click
on: 
  workflow_dispatch:
     inputs:
        options:
           description: 'Select options'
           required: true
           type: choice
           options:
             - Option 1
             - Option 2
             - Option 3
           multiple: true
          

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        az webapp list --query "[?state=='Running']" -o table
