name: Release

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
                uses: actions/checkout@v2

            - name: Set up Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: 14

            - name: Install dependencies
                run: npm ci

            - name: Build
                run: npm run build

            - name: Create release
                id: create_release
                uses: actions/create-release@v1
                with:
                    tag_name: v${{ github.run_number }}
                    release_name: Release ${{ github.run_number }}
                    body: |
                        This is an automatic release triggered by GitHub Actions.
                    draft: false
                    prerelease: false

            - name: Upload artifact
                uses: actions/upload-artifact@v2
                with:
                    name: my-artifact
                    path: dist/

            - name: Deploy
                uses: some-deployment-action@v1
                with:
                    environment: production
                    token: ${{ secrets.DEPLOYMENT_TOKEN }}
