name: Test hosted Runner.
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: [self-hosted, ubuntu24]

    steps:
      - name: Test message
        run: echo "✅ Self-hosted runner is working!"

      - name: System info
        run: |
          echo "User: $(whoami)"
          echo "Machine: $(hostname)"
          kubectl config get-contexts
          sudo -u devops -i bash -c "kubectl get pods -A"
