name: kubectl test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
jobs:
  test:
    runs-on: [self-hosted, ubuntu24]
    steps:
      - name: Setup kubeconfig
        run: |
          # mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > config
          chmod 600 config

      - name: Test cluster
        run: kubectl --kubeconfig config get pods -A
