name: Milvus DB Backup & Restore

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select action to perform'
        required: true
        default: 'backup'
        type: choice
        options:
          - backup
          - restore
      dev:
        description: 'Restore QA environment?'
        required: true
        default: 'true'
        type: boolean
      qa:
        description: 'Restore QA Demo environment?'
        required: true
        default: 'true'
        type: boolean
      uat:
        description: 'Restore Staging environment?'
        required: true
        default: 'true'
        type: boolean
      stage:
        description: 'Restore Production environment?'
        required: true
        default: 'true'
        type: boolean
