name: Environment Example
on: [push]

jobs:
  print-env:
    runs-on: ubuntu-latest
    env:
      GLOBAL_VAR: "This is global"
    steps:
      - name: Print Env Vars
        run: |
          echo "GLOBAL_VAR: $GLOBAL_VAR"
          echo "MY_VAR: $MY_VAR"
        env:
          MY_VAR: "This is a step-level var"
