name: working Dires and shells
on: [push]

defaults: 
    run:
        shell: bash
jobs: 
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display working directory
              run: | 
                pwd
                ls -l
                pwd
                ls -l $GITHUB_WORKSPACE
                echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
                echo "GITHUB_SHA: $GITHUB_SHA"
                echo "GITHUB_REF: $GITHUB_REF"
                echo "GITHUB_ACTOR: $GITHUB_ACTOR"
                echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
                echo "GITHUB_ACTION: $GITHUB_ACTION"
                echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
                echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
                echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
                echo $GITHUB_ACTION_PATH
                echo $GITHUB_ACTION_REPOSITORY	
                echo $GITHUB_ACTOR
                echo $GITHUB_ACTOR_ID
                echo $GITHUB_API_URL
                echo $GITHUB_BASE_REF
                echo $GITHUB_ENV
                echo $GITHUB_EVENT_NAME
                echo $GITHUB_EVENT_PATH
                echo $GITHUB_GRAPHQL_URL
                echo $GITHUB_HEAD_REF
                echo $GITHUB_JOB
                echo $GITHUB_OUTPUT
                echo $GITHUB_PATH
                echo $GITHUB_REF
                echo $GITHUB_REF_NAME
                echo $GITHUB_REF_PROTECTED
                echo $GITHUB_REF_TYPE
                echo $GITHUB_REPOSITORY
                echo $GITHUB_REPOSITORY_ID
                echo $GITHUB_REPOSITORY_OWNER
                echo $GITHUB_REPOSITORY_OWNER_ID	
                echo $GITHUB_RETENTION_DAYS	
                echo $GITHUB_RUN_ATTEMPT
                echo $GITHUB_RUN_ID
                echo $GITHUB_RUN_NUMBER	
                echo $GITHUB_SERVER_URL
                echo $GITHUB_SHA
                echo $GITHUB_STEP_SUMMARY
                echo $GITHUB_TRIGGERING_ACTOR
                echo $GITHUB_WORKFLOW
                echo $GITHUB_WORKFLOW_REF
                echo $GITHUB_WORKFLOW_SHA
                echo $GITHUB_WORKSPACE
                echo $RUNNER_ARCH
                echo $RUNNER_DEBUG
                echo $RUNNER_NAME
                echo $RUNNER_OS
                echo $RUNNER_TEMP
                echo $RUNNER_TOOL_CACHE
                
    display-windowsd-info:
        runs-on: windows-latest
        defaults: 
            run:
                shell: pwsh
        steps:
            - name: Display working directory
              run: | 
                Write-OutPut "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
                Write-OutPut "GITHUB_SHA: $GITHUB_SHA"
                Write-OutPut "GITHUB_REF: $GITHUB_REF"
                Write-OutPut "GITHUB_ACTOR: $GITHUB_ACTOR"
                Write-OutPut "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
                Write-OutPut "GITHUB_ACTION: $GITHUB_ACTION"
                Write-OutPut "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
                Write-OutPut "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
                Write-OutPut "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
            - name: Pyhon Shell
              shell: python
              run: | 
                import os
                print(os.getcwd())
                print(os.listdir())
                print(os.listdir(os.getcwd()))
                print(os.listdir(os.environ['GITHUB_WORKSPACE']))
                print(os.environ['GITHUB_REPOSITORY'])
                print(os.environ['GITHUB_SHA'])
                print(os.environ['GITHUB_REF'])
                print(os.environ['GITHUB_ACTOR'])
                print(os.environ['GITHUB_WORKFLOW'])
                print(os.environ['GITHUB_ACTION'])
                print(os.environ['GITHUB_EVENT_NAME'])
                print(os.environ['GITHUB_EVENT_PATH'])
                print(os.environ['GITHUB_WORKSPACE'])
