name: workflow commands
on: [push]


jobs: 
    testing-wf-commands: 
        runs-on: ubuntu-latest
        steps: 
            - name: checkout
              uses: echo "::error::Missing semicolon."