name: working Dires and shells
on: [push]

jobs: 
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display working directory
              run: | 
                pwd
                ls -l
                echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
                echo "GITHUB_SHA: $GITHUB_SHA"
                echo "GITHUB_REF: $GITHUB_REF"
                echo "GITHUB_ACTOR: $GITHUB_ACTOR"
                echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
                echo "GITHUB_ACTION: $GITHUB_ACTION"
                echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
                echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
                echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
                ls -l $GITHUB_WORKSPACE
    display-windowsd-info:
        runs-on: windows-latest
        steps:
            - name: Display working directory
              run: | 
                pwd
                ls -l
                echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
                echo "GITHUB_SHA: $GITHUB_SHA"
                echo "GITHUB_REF: $GITHUB_REF"
                echo "GITHUB_ACTOR: $GITHUB_ACTOR"
                echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
                echo "GITHUB_ACTION: $GITHUB_ACTION"
                echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
                echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
                echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
                ls -l $GITHUB_WORKSPACE